//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLauncherCSharp.String {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDLauncherCSharp.String.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Load Archive 的本地化字符串。
        /// </summary>
        public static string btnArchive_Content {
            get {
                return ResourceManager.GetString("btnArchive.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Command Line 的本地化字符串。
        /// </summary>
        public static string btnCmdClr_Content {
            get {
                return ResourceManager.GetString("btnCmdClr.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RUN! 的本地化字符串。
        /// </summary>
        public static string btnRun_Content {
            get {
                return ResourceManager.GetString("btnRun.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string btnSettings_Content {
            get {
                return ResourceManager.GetString("btnSettings.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Log 的本地化字符串。
        /// </summary>
        public static string cbLog_Content {
            get {
                return ResourceManager.GetString("cbLog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run As Administrator 的本地化字符串。
        /// </summary>
        public static string cbRunAs_Content {
            get {
                return ResourceManager.GetString("cbRunAs.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singleplayer Campaign Launcher 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Line:  的本地化字符串。
        /// </summary>
        public static string txtCommandLineTip_Text {
            get {
                return ResourceManager.GetString("txtCommandLineTip.Text", resourceCulture);
            }
        }
    }
}
