//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLauncherCSharp.String {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDLauncherCSharp.String.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Load Archive 的本地化字符串。
        /// </summary>
        public static string btnArchive_Content {
            get {
                return ResourceManager.GetString("btnArchive.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Command Line 的本地化字符串。
        /// </summary>
        public static string btnCmdClr_Content {
            get {
                return ResourceManager.GetString("btnCmdClr.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string btnExit_Content {
            get {
                return ResourceManager.GetString("btnExit.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RUN! 的本地化字符串。
        /// </summary>
        public static string btnRun_Content {
            get {
                return ResourceManager.GetString("btnRun.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string btnSettings_Content {
            get {
                return ResourceManager.GetString("btnSettings.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back Buffer 的本地化字符串。
        /// </summary>
        public static string cbBackBuffer_Content {
            get {
                return ResourceManager.GetString("cbBackBuffer.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Borderless 的本地化字符串。
        /// </summary>
        public static string cbBorderLess_Content {
            get {
                return ResourceManager.GetString("cbBorderLess.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Log 的本地化字符串。
        /// </summary>
        public static string cbLog_Content {
            get {
                return ResourceManager.GetString("cbLog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CNC-DDraw (recommended) 的本地化字符串。
        /// </summary>
        public static string cbRenderer_CNCDDraw {
            get {
                return ResourceManager.GetString("cbRenderer.CNCDDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string cbRenderer_None {
            get {
                return ResourceManager.GetString("cbRenderer.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run As Administrator 的本地化字符串。
        /// </summary>
        public static string cbRunAs_Content {
            get {
                return ResourceManager.GetString("cbRunAs.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windowed 的本地化字符串。
        /// </summary>
        public static string cbWindowed_Content {
            get {
                return ResourceManager.GetString("cbWindowed.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string dlgSaveLoader_CloseButtonContent {
            get {
                return ResourceManager.GetString("dlgSaveLoader.CloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string dlgSaveLoader_PrimaryButtonContent {
            get {
                return ResourceManager.GetString("dlgSaveLoader.PrimaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Loader 的本地化字符串。
        /// </summary>
        public static string dlgSaveLoader_Title {
            get {
                return ResourceManager.GetString("dlgSaveLoader.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string dlgSetting_CloseButtonContent {
            get {
                return ResourceManager.GetString("dlgSetting.CloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string dlgSetting_PrimaryButtonContent {
            get {
                return ResourceManager.GetString("dlgSetting.PrimaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Settings 的本地化字符串。
        /// </summary>
        public static string dlgSetting_Title {
            get {
                return ResourceManager.GetString("dlgSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Easy 的本地化字符串。
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        public static string gbDisplay_Header {
            get {
                return ResourceManager.GetString("gbDisplay.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard 的本地化字符串。
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singleplayer Campaign Launcher for Braindead RL 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This mission is ONLY supported with Ares platform.
        ///
        ///You may need to check if Ares.dll and Syringe.exe are placed in your game directory.
        ///
        ///It is advised to download again if the files above cannot be found. 的本地化字符串。
        /// </summary>
        public static string msgAresNotFoundError {
            get {
                return ResourceManager.GetString("msgAresNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Braindead Launcher 的本地化字符串。
        /// </summary>
        public static string msgCaptain {
            get {
                return ResourceManager.GetString("msgCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to load with no save files selected. 的本地化字符串。
        /// </summary>
        public static string msgNoSaveLoadedError {
            get {
                return ResourceManager.GetString("msgNoSaveLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing or invalid map loader &apos;cncnet5.dll&apos; in your game directory! 的本地化字符串。
        /// </summary>
        public static string msgSpawnerInvalidError {
            get {
                return ResourceManager.GetString("msgSpawnerInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Name 的本地化字符串。
        /// </summary>
        public static string SLArchiveName {
            get {
                return ResourceManager.GetString("SLArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Time 的本地化字符串。
        /// </summary>
        public static string SLArchiveTime {
            get {
                return ResourceManager.GetString("SLArchiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher Created By: 的本地化字符串。
        /// </summary>
        public static string txtAppAuthor {
            get {
                return ResourceManager.GetString("txtAppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command line arguments:  的本地化字符串。
        /// </summary>
        public static string txtCommandLineTip_Text {
            get {
                return ResourceManager.GetString("txtCommandLineTip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty: 的本地化字符串。
        /// </summary>
        public static string txtDifficulty_Text {
            get {
                return ResourceManager.GetString("txtDifficulty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presented by CacoNyan Studio 的本地化字符串。
        /// </summary>
        public static string txtMisAuthor {
            get {
                return ResourceManager.GetString("txtMisAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation: Braindead 的本地化字符串。
        /// </summary>
        public static string txtMisName {
            get {
                return ResourceManager.GetString("txtMisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renderer: 的本地化字符串。
        /// </summary>
        public static string txtRenderer_Text {
            get {
                return ResourceManager.GetString("txtRenderer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Size (W*H): 的本地化字符串。
        /// </summary>
        public static string txtScreenSize_Text {
            get {
                return ResourceManager.GetString("txtScreenSize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAUTION: Some of the settings may not be available. 的本地化字符串。
        /// </summary>
        public static string txtSettingTip_Text {
            get {
                return ResourceManager.GetString("txtSettingTip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special Thanks: 的本地化字符串。
        /// </summary>
        public static string txtThanks {
            get {
                return ResourceManager.GetString("txtThanks", resourceCulture);
            }
        }
    }
}
